In [3]:
from mxnet import nd

x = nd.ones(3)
y = nd.zeros(4)
filename = "../data/test1.params"
nd.save(filename, [x, y])

In [4]:
a, b = nd.load(filename)
print(a, b)


[ 1.  1.  1.]
<NDArray 3 @cpu(0)> 
[ 0.  0.  0.  0.]
<NDArray 4 @cpu(0)>


In [5]:
mydict = {"x": x, "y": y}
filename = "../data/test2.params"
nd.save(filename, mydict)
c = nd.load(filename)
print(c)

{'x': 
[ 1.  1.  1.]
<NDArray 3 @cpu(0)>, 'y': 
[ 0.  0.  0.  0.]
<NDArray 4 @cpu(0)>}
